version: '3.1'
services:
 gapi:
  #   rpc server is the main application in this service,
  # don't move build context to subfolders for sake of simplicity.
  build:
    context: .
  restart: unless-stopped
  # TODO: Use traefik labels instead of exposing ports
  env_file:
    - .env
  ports:
    - "50001:50001"
  depends_on:
    - mariadb01
  # TODO: Fetch from locally mounted env file (remove redundancy)
  environment:
    LISTEN_ADDR: ":50001"
    DB_CONNECTION: "qbsql:152535@tcp(mariadb01:3306)/qbsql?parseTime=true"
 mariadb01:
    build:
     context: ./database
    restart: unless-stopped
    # TODO: Fetch from locally mounted env file (remove redundancy)
    environment:
      MYSQL_DATABASE: qbsql
      MYSQL_USER: qbsql
      MYSQL_PASSWORD: "152535"
      MYSQL_ROOT_PASSWORD: "152535"
    # TODO: Don't lose your data. (add better persistence)
    volumes:
       - ./.volumes/data:/var/lib/mysql
