version: '3.1'
services:
 api:
  build:
    context: .
  restart: unless-stopped
  ports:
    - "50001:50001"
  depends_on:
    - mariadb01
  environment:
    LISTEN_ADDR: ":50001"
    DB_CONNECTION: "qbsql:152535@tcp(mariadb01:3306)/qbsql?parseTime=true"
 mariadb01:
    build:
     context: ./database
     dockerfile: db.Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: qbsql
      MYSQL_USER: qbsql
      MYSQL_PASSWORD: "152535"
      MYSQL_ROOT_PASSWORD: "152535"
    volumes:
       - ./volumes/data:/var/lib/mysql
