version: '3.1'
services:
 api:
  build:
    context: .
  restart: unless-stopped
  ports:
    - "50001:50001"
    - "8080:8080"
  depends_on:
    - database
  volumes:
    - ./.volumes/public:/app/public
  environment:
    LISTEN_ADDR: ":50001"
    DB_CONNECTION: "qbsql:152535@tcp(database:3306)/qbsql?parseTime=true"
 database:
    build:
     context: ./database
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - "33061:3306"
    environment:
      MYSQL_DATABASE: qbsql
      MYSQL_USER: qbsql
      MYSQL_PASSWORD: "152535"
      MYSQL_ROOT_PASSWORD: "152535"
    volumes:
       - ./.volumes/data:/var/lib/mysql
