// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: pointspb.proto

package pointspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PointsServiceClient is the client API for PointsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PointsServiceClient interface {
	GetPointsByDistrict(ctx context.Context, in *QueryByDistrict, opts ...grpc.CallOption) (*PointsByDistrict, error)
	GetUserStats(ctx context.Context, in *QueryByUser, opts ...grpc.CallOption) (*UserStats, error)
}

type pointsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointsServiceClient(cc grpc.ClientConnInterface) PointsServiceClient {
	return &pointsServiceClient{cc}
}

func (c *pointsServiceClient) GetPointsByDistrict(ctx context.Context, in *QueryByDistrict, opts ...grpc.CallOption) (*PointsByDistrict, error) {
	out := new(PointsByDistrict)
	err := c.cc.Invoke(ctx, "/points.PointsService/GetPointsByDistrict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointsServiceClient) GetUserStats(ctx context.Context, in *QueryByUser, opts ...grpc.CallOption) (*UserStats, error) {
	out := new(UserStats)
	err := c.cc.Invoke(ctx, "/points.PointsService/GetUserStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointsServiceServer is the server API for PointsService service.
// All implementations must embed UnimplementedPointsServiceServer
// for forward compatibility
type PointsServiceServer interface {
	GetPointsByDistrict(context.Context, *QueryByDistrict) (*PointsByDistrict, error)
	GetUserStats(context.Context, *QueryByUser) (*UserStats, error)
	mustEmbedUnimplementedPointsServiceServer()
}

// UnimplementedPointsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPointsServiceServer struct {
}

func (UnimplementedPointsServiceServer) GetPointsByDistrict(context.Context, *QueryByDistrict) (*PointsByDistrict, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPointsByDistrict not implemented")
}
func (UnimplementedPointsServiceServer) GetUserStats(context.Context, *QueryByUser) (*UserStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedPointsServiceServer) mustEmbedUnimplementedPointsServiceServer() {}

// UnsafePointsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointsServiceServer will
// result in compilation errors.
type UnsafePointsServiceServer interface {
	mustEmbedUnimplementedPointsServiceServer()
}

func RegisterPointsServiceServer(s grpc.ServiceRegistrar, srv PointsServiceServer) {
	s.RegisterService(&PointsService_ServiceDesc, srv)
}

func _PointsService_GetPointsByDistrict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByDistrict)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).GetPointsByDistrict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/points.PointsService/GetPointsByDistrict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).GetPointsByDistrict(ctx, req.(*QueryByDistrict))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointsService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryByUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointsServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/points.PointsService/GetUserStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointsServiceServer).GetUserStats(ctx, req.(*QueryByUser))
	}
	return interceptor(ctx, in, info, handler)
}

// PointsService_ServiceDesc is the grpc.ServiceDesc for PointsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "points.PointsService",
	HandlerType: (*PointsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPointsByDistrict",
			Handler:    _PointsService_GetPointsByDistrict_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _PointsService_GetUserStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pointspb.proto",
}
